version: '2'
services:
    mysql:
        image: mysql
        container_name: mysql_hw
        ports: 
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=16051223
            - MYSQL_DATABASE=hw
        command: [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci"
        ]
    redis: 
        image: redis
        container_name: redis_hw
        ports: 
            - '6379:6379'
        restart: always
        command: redis-server --appendonly yes